db:
  image: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: zxcv1234
  volumes:
    - ~/.mysql_data_dir:/var/lib/mysql
adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080
  links:
    - db:mysql
  environment:
    PMA_HOST: mysql_db_1
